name: slide_digital_clock
description: Digital Clock for Flutter
version: 1.0.0
homepage: https://github.com/caglarylmz/slide_digital_clock

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: